package:
  name: qapa
  version: 'v1.0.0'

source:
  git_url: https://github.com/morrislab/qapa.git

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy
    - biopython
    - pybedtools >=0.7.9

  run:
    - python
    - pandas
    - numpy
    - biopython
    - pybedtools >=0.7.9

about:
  home: https://github.com/morrislab/qapa
  license: GPL v3
  license_file: LICENSE
